// price_data.js
// Ini adalah database lokal yang diperluas untuk rentang harga Rp 1.000 - Rp 10.000.
// Berisi 90 item untuk memberikan rekomendasi yang lebih akurat dan beragam.

const productDatabase = [
  // --- Kategori: Jajanan & Makanan Ringan ---
  { "nama_produk": "Permen", "estimasi_harga": 100 },
  { "nama_produk": "Kopi Sachet Instan", "estimasi_harga": 1500 },
  { "nama_produk": "Gorengan (Tahu, Tempe, Bakwan)", "estimasi_harga": 2000 },
  { "nama_produk": "Kerupuk Putih Kaleng", "estimasi_harga": 2000 },
  { "nama_produk": "Permen Karet", "estimasi_harga": 2500 },
  { "nama_produk": "Wafer Coklat Satuan", "estimasi_harga": 2500 },
  { "nama_produk": "Biskuit Krim Sachet", "estimasi_harga": 3000 },
  { "nama_produk": "Coklat Batang Kecil", "estimasi_harga": 4000 },
  { "nama_produk": "Snack Kentang (Chitato Sachet)", "estimasi_harga": 5000 },
  { "nama_produk": "Kacang Atom Bungkus Kecil", "estimasi_harga": 5000 },
  { "nama_produk": "Roti Tawar Satuan", "estimasi_harga": 6000 },
  { "nama_produk": "Agar-agar Sachet", "estimasi_harga": 4500 },
  { "nama_produk": "Puding Sachet", "estimasi_harga": 6000 },
  { "nama_produk": "Kue Basah di Pasar", "estimasi_harga": 2500 },
  { "nama_produk": "Lontong Isi Sayur", "estimasi_harga": 3000 },
  { "nama_produk": "Mie Lidi", "estimasi_harga": 5000 },
  { "nama_produk": "Popcorn Sachet (untuk microwave)", "estimasi_harga": 8000 },
  { "nama_produk": "Jelly Minuman Gelas", "estimasi_harga": 2000 },
  { "nama_produk": "Cilok/Cimol porsi kecil", "estimasi_harga": 5000 },
  { "nama_produk": "Telur Gulung (per tusuk)", "estimasi_harga": 2000 },
  { "nama_produk": "Permen Kaki", "estimasi_harga": 1500 },

  // --- Kategori: Minuman ---
  { "nama_produk": "Air Mineral Gelas", "estimasi_harga": 1000 },
  { "nama_produk": "Minuman Sachet (Jasjus, Marimas)", "estimasi_harga": 1000 },
  { "nama_produk": "Teh Celup Satuan", "estimasi_harga": 1000 },
  { "nama_produk": "Air Mineral Botol 600ml", "estimasi_harga": 3500 },
  { "nama_produk": "Teh Kotak Kecil", "estimasi_harga": 4000 },
  { "nama_produk": "Susu UHT Kotak Kecil", "estimasi_harga": 5000 },
  { "nama_produk": "Minuman Isotonik Botol", "estimasi_harga": 7000 },
  { "nama_produk": "Kopi Botol Siap Minum", "estimasi_harga": 8000 },
  { "nama_produk": "Es Teh Manis di Warung", "estimasi_harga": 4000 },
  { "nama_produk": "Minuman Cincau Kaleng", "estimasi_harga": 8500 },
  { "nama_produk": "Yogurt Drink Botol Kecil", "estimasi_harga": 9000 },
  { "nama_produk": "Susu Kental Manis Sachet", "estimasi_harga": 2000 },
  { "nama_produk": "Minuman Sari Kacang Hijau", "estimasi_harga": 6000 },
  { "nama_produk": "Minuman Jambu Kotak", "estimasi_harga": 7000 },
  { "nama_produk": "Es Batu Kristal (1 kantong)", "estimasi_harga": 2000 },

  // --- Kategori: Alat Tulis Kantor (ATK) ---
  { "nama_produk": "Pulpen Standar", "estimasi_harga": 3000 },
  { "nama_produk": "Pensil 2B", "estimasi_harga": 2500 },
  { "nama_produk": "Penghapus Kecil", "estimasi_harga": 2000 },
  { "nama_produk": "Rautan Pensil", "estimasi_harga": 3000 },
  { "nama_produk": "Penggaris Plastik 30cm", "estimasi_harga": 4000 },
  { "nama_produk": "Buku Tulis Tipis (38 lembar)", "estimasi_harga": 3500 },
  { "nama_produk": "Lem Kertas Stik Kecil", "estimasi_harga": 5000 },
  { "nama_produk": "Spidol Papan Tulis Satuan", "estimasi_harga": 8000 },
  { "nama_produk": "Isi Staples Kecil", "estimasi_harga": 4000 },
  { "nama_produk": "Kertas Kado (1 lembar)", "estimasi_harga": 3000 },
  { "nama_produk": "Amplop Putih Panjang (10 pcs)", "estimasi_harga": 5000 },
  { "nama_produk": "Sticky Notes Ukuran Kecil", "estimasi_harga": 7000 },
  { "nama_produk": "Tipe-X / Correction Pen Kecil", "estimasi_harga": 9000 },
  { "nama_produk": "Jangka Sekolah", "estimasi_harga": 8500 },
  { "nama_produk": "Sampul Buku Plastik/Mika", "estimasi_harga": 2000 },

  // --- Kategori: Kebutuhan Dapur & Masak ---
  { "nama_produk": "Bumbu Masak Sachet (Royco, Masako)", "estimasi_harga": 1000 },
  { "nama_produk": "Santan Instan Sachet Kecil", "estimasi_harga": 3000 },
  { "nama_produk": "Kecap Manis Sachet", "estimasi_harga": 2000 },
  { "nama_produk": "Saus Sambal Sachet", "estimasi_harga": 1500 },
  { "nama_produk": "Terasi Sachet", "estimasi_harga": 2000 },
  { "nama_produk": "Mie Instan Goreng", "estimasi_harga": 3500 },
  { "nama_produk": "Mie Instan Rebus", "estimasi_harga": 3000 },
  { "nama_produk": "Telur Ayam (1 butir)", "estimasi_harga": 2500 },
  { "nama_produk": "Bawang Merah (ons)", "estimasi_harga": 4000 },
  { "nama_produk": "Bawang Putih (ons)", "estimasi_harga": 3500 },
  { "nama_produk": "Cabe Rawit (ons)", "estimasi_harga": 6000 },
  { "nama_produk": "Tahu Putih (1 potong besar)", "estimasi_harga": 3000 },
  { "nama_produk": "Tempe (1 papan kecil)", "estimasi_harga": 4000 },
  { "nama_produk": "Sayur Bayam/Kangkung (1 ikat)", "estimasi_harga": 3000 },
  { "nama_produk": "Garam Meja Bungkus Kecil", "estimasi_harga": 2000 },

  // --- Kategori: Kebersihan & Perawatan Diri ---
  { "nama_produk": "Sabun Mandi Batang", "estimasi_harga": 4000 },
  { "nama_produk": "Shampo Sachet", "estimasi_harga": 1000 },
  { "nama_produk": "Pasta Gigi Sachet/Kecil", "estimasi_harga": 5000 },
  { "nama_produk": "Sikat Gigi Ekonomi", "estimasi_harga": 6000 },
  { "nama_produk": "Deterjen Sachet (sekali cuci)", "estimasi_harga": 1500 },
  { "nama_produk": "Pewangi Pakaian Sachet", "estimasi_harga": 1000 },
  { "nama_produk": "Sabun Cuci Piring Sachet", "estimasi_harga": 2000 },
  { "nama_produk": "Tisu Wajah Saku", "estimasi_harga": 3000 },
  { "nama_produk": "Cotton Bud (kemasan kecil)", "estimasi_harga": 4000 },
  { "nama_produk": "Pembalut Wanita (2-3 pcs)", "estimasi_harga": 5000 },
  { "nama_produk": "Deodorant Sachet", "estimasi_harga": 2500 },
  { "nama_produk": "Minyak Kayu Putih Botol Kecil", "estimasi_harga": 9500 },
  { "nama_produk": "Pembersih Lantai Sachet", "estimasi_harga": 2000 },
  { "nama_produk": "Korek Api Gas", "estimasi_harga": 3000 },
  { "nama_produk": "Lilin Mati Lampu", "estimasi_harga": 2000 },

  // --- Kategori: Lain-lain ---
  { "nama_produk": "Materai 10000", "estimasi_harga": 10000 },
  { "nama_produk": "Parkir Motor (1 jam)", "estimasi_harga": 2000 },
  { "nama_produk": "Ongkos Angkot (jarak dekat)", "estimasi_harga": 5000 },
  { "nama_produk": "Baterai AA/AAA (1 buah)", "estimasi_harga": 4000 },
  { "nama_produk": "Jasa Tambal Ban Motor", "estimasi_harga": 10000 },
  { "nama_produk": "Isi Angin Ban Motor", "estimasi_harga": 2000 },
  { "nama_produk": "Fotokopi (1 lembar)", "estimasi_harga": 500 },
  { "nama_produk": "Jarum & Benang Jahit", "estimasi_harga": 5000 },
  { "nama_produk": "Peniti (1 set)", "estimasi_harga": 2000 },
  { "nama_produk": "Obat Sakit Kepala (1 strip)", "estimasi_harga": 8000 },

  // --- Kategori: Rp 10.000 - Rp 20.000 ---
  { "nama_produk": "Nasi Uduk Lauk Sederhana", "estimasi_harga": 12000 },
  { "nama_produk": "Bubur Ayam Porsi Kecil", "estimasi_harga": 10000 },
  { "nama_produk": "Roti Sobek Coklat", "estimasi_harga": 12000 },
  { "nama_produk": "Susu UHT 1 Liter", "estimasi_harga": 17000 },
  { "nama_produk": "Siomay Porsi Sedang", "estimasi_harga": 15000 },
  { "nama_produk": "Batagor Porsi Sedang", "estimasi_harga": 15000 },
  { "nama_produk": "Gula Pasir 1kg", "estimasi_harga": 16000 },
  { "nama_produk": "Tepung Terigu 1kg", "estimasi_harga": 14000 },
  { "nama_produk": "Telur Ayam (1/2 kg)", "estimasi_harga": 16000 },
  { "nama_produk": "Margarin Sachet Besar", "estimasi_harga": 11000 },
  { "nama_produk": "Kecap Manis Botol Kecil", "estimasi_harga": 15000 },
  { "nama_produk": "Saus Tomat Botol Kecil", "estimasi_harga": 12000 },
  { "nama_produk": "Kopi Bubuk 165g", "estimasi_harga": 15000 },
  { "nama_produk": "Teh Celup Kotak (isi 25)", "estimasi_harga": 12000 },
  { "nama_produk": "Sabun Mandi Cair Pouch 250ml", "estimasi_harga": 18000 },
  { "nama_produk": "Shampo Botol Kecil", "estimasi_harga": 19000 },
  { "nama_produk": "Pasta Gigi Ukuran Sedang", "estimasi_harga": 15000 },
  { "nama_produk": "Deodorant Roll-on", "estimasi_harga": 17000 },
  { "nama_produk": "Sabun Cuci Piring Pouch 400ml", "estimasi_harga": 13000 },
  { "nama_produk": "Pembersih Lantai Pouch 400ml", "estimasi_harga": 11000 },
  { "nama_produk": "Pengharum Ruangan Semprot", "estimasi_harga": 18000 },
  { "nama_produk": "Tisu Gulung Toilet (4 roll)", "estimasi_harga": 16000 },
  { "nama_produk": "Kapas Wajah (kemasan sedang)", "estimasi_harga": 15000 },
  { "nama_produk": "Baterai Alkaline AA/AAA (isi 2)", "estimasi_harga": 16000 },
  { "nama_produk": "Obat Nyamuk Bakar (1 box)", "estimasi_harga": 12000 },
  { "nama_produk": "Plastik Sampah Gulung", "estimasi_harga": 15000 },
  { "nama_produk": "Spons Cuci Piring (isi 3)", "estimasi_harga": 11000 },
  { "nama_produk": "Buku Tulis Tebal (100 lembar)", "estimasi_harga": 12000 },
  { "nama_produk": "Pulpen Gel (Pilot, Standard)", "estimasi_harga": 15000 },
  { "nama_produk": "Spidol Marker Permanen", "estimasi_harga": 11000 },
  { "nama_produk": "Double Tape Busa", "estimasi_harga": 13000 },
  { "nama_produk": "Cutter Kecil + Isi", "estimasi_harga": 16000 },
  { "nama_produk": "Kaos Kaki Sekolah/Kantor", "estimasi_harga": 15000 },
  { "nama_produk": "Masker Medis (isi 10)", "estimasi_harga": 12000 },
  { "nama_produk": "Handsanitizer Botol Kecil", "estimasi_harga": 18000 },
  { "nama_produk": "Pulsa 10rb", "estimasi_harga": 12000 },
  { "nama_produk": "Paket Data Internet Kuota Kecil", "estimasi_harga": 15000 },
  { "nama_produk": "Topi Kupluk / Beanie", "estimasi_harga": 20000 },
  { "nama_produk": "Ikat Pinggang Kain", "estimasi_harga": 18000 },
  { "nama_produk": "Sarung Tangan Motor", "estimasi_harga": 20000 },
  { "nama_produk": "Gantungan Kunci Unik", "estimasi_harga": 15000 },
  { "nama_produk": "Es Krim Cone", "estimasi_harga": 11000 },
  { "nama_produk": "Voucher Game Online", "estimasi_harga": 12000 },
  { "nama_produk": "Pisau Dapur Kecil", "estimasi_harga": 18000 },
  { "nama_produk": "Talenan Kayu Kecil", "estimasi_harga": 15000 },
  { "nama_produk": "Gelas Kaca / Mug", "estimasi_harga": 17000 },
  { "nama_produk": "Mangkok Melamin", "estimasi_harga": 14000 },
  { "nama_produk": "Sendok & Garpu (set)", "estimasi_harga": 20000 },
  // Lanjutan Kategori: Di Bawah Rp 10.000
{ "nama_produk": "Isi Staples", "estimasi_harga": 4000 },
{ "nama_produk": "Spidol Papan Tulis", "estimasi_harga": 8500 },
{ "nama_produk": "Lem Kertas Stik", "estimasi_harga": 5000 },
{ "nama_produk": "Tali Rafia Gulungan Kecil", "estimasi_harga": 7000 },
{ "nama_produk": "Korek Api Gas", "estimasi_harga": 3500 },
{ "nama_produk": "Fotokopi/Print per Lembar", "estimasi_harga": 500 },
{ "nama_produk": "Jarum & Benang Set", "estimasi_harga": 6000 },
{ "nama_produk": "Peniti Set", "estimasi_harga": 3000 },
{ "nama_produk": "Kertas Kado", "estimasi_harga": 2500 },
{ "nama_produk": "Stiker Anak-Anak", "estimasi_harga": 4000 },
{ "nama_produk": "Sampo Sachet (Renceng)", "estimasi_harga": 9500 },
{ "nama_produk": "Masker Wajah Sachet", "estimasi_harga": 8000 },

// Lanjutan Kategori: Rp 10.000 - Rp 50.000
{ "nama_produk": "Masker Kain 3 Lapis", "estimasi_harga": 15000 },
{ "nama_produk": "Tempat Pensil Sederhana", "estimasi_harga": 25000 },
{ "nama_produk": "Penggaris Besi 30cm", "estimasi_harga": 12000 },
{ "nama_produk": "Deterjen Cair Pouch", "estimasi_harga": 21000 },
{ "nama_produk": "Minyak Goreng 1 Liter", "estimasi_harga": 24000 },
{ "nama_produk": "Kaus Dalam Pria", "estimasi_harga": 35000 },
{ "nama_produk": "Bohlam LED 10 Watt", "estimasi_harga": 28000 },
{ "nama_produk": "Casing HP Silikon", "estimasi_harga": 40000 },
{ "nama_produk": "Obat Nyamuk Elektrik + Refill", "estimasi_harga": 32000 },
{ "nama_produk": "Pewangi Pakaian Botol", "estimasi_harga": 18000 },
{ "nama_produk": "Talenan Kayu", "estimasi_harga": 26000 },
{ "nama_produk": "Spatula Silikon", "estimasi_harga": 30000 },

// Lanjutan Kategori: Rp 50.000 - Rp 250.000
{ "nama_produk": "Jas Hujan Setelan", "estimasi_harga": 80000 },
{ "nama_produk": "Handuk Mandi Dewasa", "estimasi_harga": 95000 },
{ "nama_produk": "Flashdisk 32GB", "estimasi_harga": 75000 },
{ "nama_produk": "Termos Air Panas 1 Liter", "estimasi_harga": 110000 },
{ "nama_produk": "Gembok Pengaman", "estimasi_harga": 60000 },
{ "nama_produk": "Helm Sepeda", "estimasi_harga": 200000 },
{ "nama_produk": "Tripod Mini untuk HP", "estimasi_harga": 85000 },
{ "nama_produk": "Ikat Pinggang Kulit Sintetis", "estimasi_harga": 120000 },
{ "nama_produk": "Tikar Lipat Piknik", "estimasi_harga": 130000 },
{ "nama_produk": "Pompa Angin Ban Sepeda", "estimasi_harga": 100000 },
{ "nama_produk": "Gunting Rambut Manual", "estimasi_harga": 70000 },
{ "nama_produk": "Panci Rebus Mie Instan", "estimasi_harga": 65000 },

// Lanjutan Kategori: Rp 250.000 - Rp 1.000.000
{ "nama_produk": "Sepatu Pantofel Kerja", "estimasi_harga": 450000 },
{ "nama_produk": "Bor Listrik Tangan", "estimasi_harga": 500000 },
{ "nama_produk": "Rak Buku Dinding Minimalis", "estimasi_harga": 350000 },
{ "nama_produk": "Wajan Teflon Set (3 buah)", "estimasi_harga": 400000 },
{ "nama_produk": "Mikrofon Kondenser untuk PC", "estimasi_harga": 600000 },
{ "nama_produk": "Speaker Aktif Komputer", "estimasi_harga": 700000 },
{ "nama_produk": "Galon Air Minum Isi Ulang (plus galon)", "estimasi_harga": 280000 },
{ "nama_produk": "Meja Lipat Laptop", "estimasi_harga": 320000 },
{ "nama_produk": "Koper Kabin", "estimasi_harga": 800000 },
{ "nama_produk": "Cat Tembok 5kg", "estimasi_harga": 270000 },
{ "nama_produk": "Aquarium Kaca Kecil", "estimasi_harga": 300000 },

// Lanjutan Kategori: Rp 1.000.000 - Rp 5.000.000
{ "nama_produk": "Mesin Jahit Portable", "estimasi_harga": 2100000 },
{ "nama_produk": "Smart TV 32 inch", "estimasi_harga": 2500000 },
{ "nama_produk": "Dispenser Galon Bawah", "estimasi_harga": 1900000 },
{ "nama_produk": "Kasur Busa (Ukuran Single)", "estimasi_harga": 1500000 },
{ "nama_produk": "Oven Listrik", "estimasi_harga": 1200000 },
{ "nama_produk": "Air Cooler", "estimasi_harga": 1300000 },
{ "nama_produk": "PlayStation 3 Bekas", "estimasi_harga": 1700000 },
{ "nama_produk": "CCTV Paket 2 Kamera", "estimasi_harga": 2800000 },
{ "nama_produk": "Genset Mini Portable", "estimasi_harga": 3500000 },
{ "nama_produk": "Stroller Bayi", "estimasi_harga": 1600000 },

// Lanjutan Kategori: Rp 5.000.000 - Rp 15.000.000
{ "nama_produk": "Sofa 2-Seater", "estimasi_harga": 7000000 },
{ "nama_produk": "Kamera DSLR Entry-Level (Kit)", "estimasi_harga": 8500000 },
{ "nama_produk": "Tempat Tidur Set (Queen Size)", "estimasi_harga": 9000000 },
{ "nama_produk": "Water Heater Gas", "estimasi_harga": 6000000 },
{ "nama_produk": "Biaya Pembuatan SIM A", "estimasi_harga": 5500000 },
{ "nama_produk": "Velg Mobil Racing (Set)", "estimasi_harga": 12000000 },
{ "nama_produk": "Lemari Dapur (Kitchen Set Mini)", "estimasi_harga": 10000000 },
{ "nama_produk": "Laptop Chromebook", "estimasi_harga": 5800000 },
{ "nama_produk": "Biola Akustik", "estimasi_harga": 6500000 },
{ "nama_produk": "Meja Billiard Mini", "estimasi_harga": 11000000 },
{ "nama_produk": "Sound System untuk Mobil", "estimasi_harga": 8000000 },

// Lanjutan Kategori: Rp 15.000.000 - Rp 50.000.000
{ "nama_produk": "Biaya Pasang Kawat Gigi", "estimasi_harga": 18000000 },
{ "nama_produk": "DP Motor Sport 150cc", "estimasi_harga": 20000000 },
{ "nama_produk": "Meja Makan Set (6 Kursi Jati)", "estimasi_harga": 16000000 },
{ "nama_produk": "Laptop Ultrabook Core i7", "estimasi_harga": 22000000 },
{ "nama_produk": "Paket Umroh Ekonomi", "estimasi_harga": 35000000 },
{ "nama_produk": "Drone DJI Mini Series", "estimasi_harga": 17000000 },
{ "nama_produk": "Piano Digital", "estimasi_harga": 25000000 },
{ "nama_produk": "Gerobak Usaha Makanan", "estimasi_harga": 19000000 },
{ "nama_produk": "TV QLED 55 inch", "estimasi_harga": 28000000 },

// Lanjutan Kategori: Rp 50.000.000 - Rp 100.000.000
{ "nama_produk": "Renovasi Atap Rumah", "estimasi_harga": 70000000 },
{ "nama_produk": "Paket Liburan Keluarga ke Jepang", "estimasi_harga": 80000000 },
{ "nama_produk": "Modal Awal Usaha Kafe Kecil", "estimasi_harga": 90000000 },
{ "nama_produk": "Satu Set Perhiasan Berlian", "estimasi_harga": 85000000 },
{ "nama_produk": "Biaya Pemasangan Panel Surya Rumahan", "estimasi_harga": 60000000 },
{ "nama_produk": "Motor Trail 150cc Baru", "estimasi_harga": 55000000 },
// Lanjutan Kategori: Di Bawah Rp 10.000
{ "nama_produk": "Lilin Mati Lampu (isi 5)", "estimasi_harga": 9000 },
{ "nama_produk": "Plester Luka (1 pack)", "estimasi_harga": 7500 },
{ "nama_produk": "Minyak Kayu Putih Botol Kecil", "estimasi_harga": 8000 },
{ "nama_produk": "Kacang Kulit Garudafood", "estimasi_harga": 6000 },
{ "nama_produk": "Kantong Sampah Gulung", "estimasi_harga": 9500 },
{ "nama_produk": "Bubur Bayi Sachet", "estimasi_harga": 7000 },
{ "nama_produk": "Spons Cuci Piring", "estimasi_harga": 4000 },
{ "nama_produk": "Gula Pasir 1/4 kg", "estimasi_harga": 5000 },
{ "nama_produk": "Karet Gelang (1 bungkus)", "estimasi_harga": 3000 },
{ "nama_produk": "Jepitan Jemuran (1 set)", "estimasi_harga": 8500 },
{ "nama_produk": "Tepung Terigu 1/2 kg", "estimasi_harga": 6500 },
{ "nama_produk": "Batu Baterai Jam Dinding", "estimasi_harga": 5000 },

// Lanjutan Kategori: Rp 10.000 - Rp 50.000
{ "nama_produk": "Vitamin C Botol Kecil", "estimasi_harga": 22000 },
{ "nama_produk": "Pelembab Bibir (Lip Balm)", "estimasi_harga": 28000 },
{ "nama_produk": "Kabel Roll Pendek (3 meter)", "estimasi_harga": 48000 },
{ "nama_produk": "Saringan Teh Stainless", "estimasi_harga": 18000 },
{ "nama_produk": "Cokelat Batang Silverqueen", "estimasi_harga": 15000 },
{ "nama_produk": "Tisu Basah Bayi", "estimasi_harga": 17000 },
{ "nama_produk": "Pengharum Ruangan Semprot", "estimasi_harga": 25000 },
{ "nama_produk": "Celana Dalam Pria (1 pcs)", "estimasi_harga": 30000 },
{ "nama_produk": "Kuas Cat Tembok", "estimasi_harga": 14000 },
{ "nama_produk": "Pisau Dapur Kecil", "estimasi_harga": 20000 },
{ "nama_produk": "Mainan Kucing (Bola Kerincing)", "estimasi_harga": 19000 },
{ "nama_produk": "Obeng Set Kecil", "estimasi_harga": 45000 },

// Lanjutan Kategori: Rp 50.000 - Rp 250.000
{ "nama_produk": "Kaos Band/Grafis", "estimasi_harga": 150000 },
{ "nama_produk": "Mainan Lego Set Kecil", "estimasi_harga": 220000 },
{ "nama_produk": "Tali Skipping (Lompat Tali)", "estimasi_harga": 90000 },
{ "nama_produk": "Baju Renang Anak", "estimasi_harga": 120000 },
{ "nama_produk": "Helm Proyek", "estimasi_harga": 65000 },
{ "nama_produk": "Kanvas Lukis 30x40cm", "estimasi_harga": 55000 },
{ "nama_produk": "Filter Air Keran", "estimasi_harga": 80000 },
{ "nama_produk": "Kacamata Baca (Plus/Minus Rendah)", "estimasi_harga": 100000 },
{ "nama_produk": "Alat Catok Rambut Mini", "estimasi_harga": 135000 },
{ "nama_produk": "Kotak P3K Isi Standar", "estimasi_harga": 110000 },
{ "nama_produk": "Steker Listrik T-Arde", "estimasi_harga": 58000 },
{ "nama_produk": "Pembersih Kaca Jendela", "estimasi_harga": 72000 },

// Lanjutan Kategori: Rp 250.000 - Rp 1.000.000
{ "nama_produk": "Sepatu Lari Entry-Level", "estimasi_harga": 550000 },
{ "nama_produk": "Meja Setrika Lipat", "estimasi_harga": 380000 },
{ "nama_produk": "Router WiFi", "estimasi_harga": 450000 },
{ "nama_produk": "Tas Kamera DSLR", "estimasi_harga": 400000 },
{ "nama_produk": "Stand Mixer Tangan", "estimasi_harga": 500000 },
{ "nama_produk": "Rak Piring Stainless", "estimasi_harga": 320000 },
{ "nama_produk": "Car Seat Cover (Sarung Jok Mobil)", "estimasi_harga": 800000 },
{ "nama_produk": "Tangga Lipat Aluminium 1.5m", "estimasi_harga": 600000 },
{ "nama_produk": "Sajadah Turki Tebal", "estimasi_harga": 280000 },
{ "nama_produk": "Cermin Rias dengan Lampu LED", "estimasi_harga": 350000 },
{ "nama_produk": "Bingkai Foto Digital", "estimasi_harga": 900000 },

// Lanjutan Kategori: Rp 1.000.000 - Rp 5.000.000
{ "nama_produk": "Mesin Cuci 2 Tabung", "estimasi_harga": 2200000 },
{ "nama_produk": "Car Seat Bayi", "estimasi_harga": 1800000 },
{ "nama_produk": "TV Box Android", "estimasi_harga": 1100000 },
{ "nama_produk": "Sepeda Anak Roda 4", "estimasi_harga": 1300000 },
{ "nama_produk": "Alat Fitness (Dumbbell Set)", "estimasi_harga": 1500000 },
{ "nama_produk": "Scanner Dokumen", "estimasi_harga": 2800000 },
{ "nama_produk": "Meja Rias Minimalis", "estimasi_harga": 1700000 },
{ "nama_produk": "Akuarium Ikan Hias Lengkap", "estimasi_harga": 3000000 },
{ "nama_produk": "Biola Pemula", "estimasi_harga": 1200000 },
{ "nama_produk": "Tenda Camping Kapasitas 4 Orang", "estimasi_harga": 1600000 },

// Lanjutan Kategori: Rp 5.000.000 - Rp 15.000.000
{ "nama_produk": "Biaya Perbaikan Bodi Mobil (Penyok)", "estimasi_harga": 6000000 },
{ "nama_produk": "Mesin Potong Rumput Dorong", "estimasi_harga": 7500000 },
{ "nama_produk": "Kitchen Set (Bagian Atas Saja)", "estimasi_harga": 9000000 },
{ "nama_produk": "Gimbal Stabilizer untuk Kamera", "estimasi_harga": 8000000 },
{ "nama_produk": "Kursi Gaming Profesional", "estimasi_harga": 6500000 },
{ "nama_produk": "Box Bayi Kayu Jati", "estimasi_harga": 5500000 },
{ "nama_produk": "PC Rakitan Kantor (Core i3)", "estimasi_harga": 7000000 },
{ "nama_produk": "Drum Elektrik Entry-Level", "estimasi_harga": 10000000 },
{ "nama_produk": "GoPro HERO Series", "estimasi_harga": 7200000 },

// Lanjutan Kategori: Rp 15.000.000 - Rp 50.000.000
{ "nama_produk": "Biaya Paket Aqiqah (2 Kambing)", "estimasi_harga": 17000000 },
{ "nama_produk": "Lensa Telephoto (Entry)", "estimasi_harga": 20000000 },
{ "nama_produk": "Paket Liburan Keluarga ke Bali (4 hari)", "estimasi_harga": 25000000 },
{ "nama_produk": "Motor Bebek Baru", "estimasi_harga": 19000000 },
{ "nama_produk": "Biaya Perpanjang STNK Mobil (5 Tahunan)", "estimasi_harga": 16000000 },
{ "nama_produk": "Sistem Audio Mobil Lengkap", "estimasi_harga": 22000000 },
{ "nama_produk": "Gazebo Kayu Kelapa", "estimasi_harga": 30000000 },
{ "nama_produk": "Mac Mini M2", "estimasi_harga": 21000000 },

// Lanjutan Kategori: Rp 50.000.000 - Rp 100.000.000
{ "nama_produk": "Uang Muka Cicilan Ruko", "estimasi_harga": 100000000 },
{ "nama_produk": "Franchise Minuman Boba (Paket Hemat)", "estimasi_harga": 75000000 },
{ "nama_produk": "Biaya Catering Pernikahan (100 Orang)", "estimasi_harga": 60000000 },
{ "nama_produk": "Motor Sport 250cc Bekas", "estimasi_harga": 55000000 },
{ "nama_produk": "Biaya Pemasangan Pagar Rumah Otomatis", "estimasi_harga": 80000000 },

// Kategori Baru: Di Atas Rp 100.000.000
{ "nama_produk": "Mobil LCGC Bekas", "estimasi_harga": 110000000 },
{ "nama_produk": "Biaya Bangun Rumah Tipe 36 (Sederhana)", "estimasi_harga": 150000000 },
{ "nama_produk": "Modal Awal Franchise Restoran Cepat Saji", "estimasi_harga": 300000000 },
{ "nama_produk": "Mobil SUV Bekas", "estimasi_harga": 250000000 },

// Lanjutan Kategori: Di Bawah Rp 10.000
{ "nama_produk": "Makanan Ikan Hias Botol Kecil", "estimasi_harga": 8000 },
{ "nama_produk": "Balsem Gosok", "estimasi_harga": 9500 },
{ "nama_produk": "Jepit Rambut (1 set)", "estimasi_harga": 7000 },
{ "nama_produk": "Kopi Bubuk Kapal Api Sachet", "estimasi_harga": 1500 },
{ "nama_produk": "Obat Sakit Kepala (1 strip)", "estimasi_harga": 3000 },
{ "nama_produk": "Garam Dapur 250g", "estimasi_harga": 4000 },
{ "nama_produk": "Vetsin / MSG 100g", "estimasi_harga": 5000 },
{ "nama_produk": "Sumpit Bambu (1 set)", "estimasi_harga": 6000 },
{ "nama_produk": "Tali Sepatu", "estimasi_harga": 8500 },
{ "nama_produk": "Kertas Amplas per Lembar", "estimasi_harga": 4500 },
{ "nama_produk": "Benang Kasur", "estimasi_harga": 5500 },

// Lanjutan Kategori: Rp 10.000 - Rp 50.000
{ "nama_produk": "Makanan Kucing Pouch (Whiskas/Friskies)", "estimasi_harga": 12000 },
{ "nama_produk": "Kacamata Renang Anak", "estimasi_harga": 45000 },
{ "nama_produk": "Mousepad Polos", "estimasi_harga": 25000 },
{ "nama_produk": "Buku Gambar A4", "estimasi_harga": 15000 },
{ "nama_produk": "Crayon Set (12 Warna)", "estimasi_harga": 22000 },
{ "nama_produk": "Lakban Bening/Coklat", "estimasi_harga": 13000 },
{ "nama_produk": "Ember Plastik Sedang", "estimasi_harga": 30000 },
{ "nama_produk": "Gayung Air", "estimasi_harga": 11000 },
{ "nama_produk": "Pembuka Botol", "estimasi_harga": 18000 },
{ "nama_produk": "Lap Kanebo", "estimasi_harga": 28000 },
{ "nama_produk": "Toples Kaca Kecil", "estimasi_harga": 35000 },

// Lanjutan Kategori: Rp 50.000 - Rp 250.000
{ "nama_produk": "Bola Basket", "estimasi_harga": 180000 },
{ "nama_produk": "Raket Badminton Pemula (plus senar)", "estimasi_harga": 150000 },
{ "nama_produk": "Umpan Pancing (1 set)", "estimasi_harga": 80000 },
{ "nama_produk": "Album Foto 4R", "estimasi_harga": 70000 },
{ "nama_produk": "Kunci Inggris", "estimasi_harga": 90000 },
{ "nama_produk": "Tas Pinggang (Waist Bag)", "estimasi_harga": 110000 },
{ "nama_produk": "Sleeping Bag Tipis", "estimasi_harga": 160000 },
{ "nama_produk": "Dasi Pria", "estimasi_harga": 75000 },
{ "nama_produk": "Kain Sarung Wadimor", "estimasi_harga": 65000 },
{ "nama_produk": "Parfum Pakaian (Laundry)", "estimasi_harga": 55000 },
{ "nama_produk": "Tempat Tidur Kucing/Anjing Kecil", "estimasi_harga": 130000 },
{ "nama_produk": "Tensi Meter Digital", "estimasi_harga": 240000 },

// Lanjutan Kategori: Rp 250.000 - Rp 1.000.000
{ "nama_produk": "Skateboard Fullset", "estimasi_harga": 700000 },
{ "nama_produk": "Matras Yoga Tebal", "estimasi_harga": 300000 },
{ "nama_produk": "Panci Presto 3L", "estimasi_harga": 450000 },
{ "nama_produk": "Sepatu Futsal Specs/Ortuseight", "estimasi_harga": 400000 },
{ "nama_produk": "Drill (Mesin Bor) Tembok", "estimasi_harga": 550000 },
{ "nama_produk": "Joran Pancing (Reel dijual terpisah)", "estimasi_harga": 350000 },
{ "nama_produk": "Cooler Box / Kotak Pendingin", "estimasi_harga": 480000 },
{ "nama_produk": "Air Fryer (Kapasitas Kecil)", "estimasi_harga": 650000 },
{ "nama_produk": "Kandang Burung Besi", "estimasi_harga": 280000 },
{ "nama_produk": "Mikroskop Mainan Edukasi", "estimasi_harga": 500000 },
{ "nama_produk": "Blazer Wanita", "estimasi_harga": 380000 },

// Lanjutan Kategori: Rp 1.000.000 - Rp 5.000.000
{ "nama_produk": "Gitar Elektrik Pemula (Paket)", "estimasi_harga": 2500000 },
{ "nama_produk": "Keyboard (Alat Musik) Yamaha PSR Series", "estimasi_harga": 3000000 },
{ "nama_produk": "Meja Pingpong / Tenis Meja", "estimasi_harga": 2800000 },
{ "nama_produk": "Treadmill Manual", "estimasi_harga": 2200000 },
{ "nama_produk": "Nintendo Switch Lite", "estimasi_harga": 3200000 },
{ "nama_produk": "Teleskop Astronomi Pemula", "estimasi_harga": 1800000 },
{ "nama_produk": "Buffet TV Minimalis", "estimasi_harga": 1500000 },
{ "nama_produk": "Pompa Air Pendorong (Booster)", "estimasi_harga": 1200000 },
{ "nama_produk": "GPS untuk Mobil", "estimasi_harga": 1100000 },
{ "nama_produk": "Papan Catur Kayu Profesional", "estimasi_harga": 1300000 },

// Lanjutan Kategori: Rp 5.000.000 - Rp 15.000.000
{ "nama_produk": "Kayak / Kano Single", "estimasi_harga": 8000000 },
{ "nama_produk": "Lensa Kamera Wide Angle (Third Party)", "estimasi_harga": 6000000 },
{ "nama_produk": "Membership Gym (1 Tahun)", "estimasi_harga": 5500000 },
{ "nama_produk": "Sepeda Statis Magnetik", "estimasi_harga": 7000000 },
{ "nama_produk": "Mesin Jahit Komputerisasi", "estimasi_harga": 9000000 },
{ "nama_produk": "Oculus Quest 2 (VR Headset)", "estimasi_harga": 7500000 },
{ "nama_produk": "Sapi Kurban (Tipe Standar)", "estimasi_harga": 14000000 },
{ "nama_produk": "Sound System Portable Rapat", "estimasi_harga": 6500000 },
{ "nama_produk": "Apple Watch SE", "estimasi_harga": 5800000 },

// Lanjutan Kategori: Rp 15.000.000 - Rp 50.000.000
{ "nama_produk": "Paket Tour Diving Raja Ampat (Hemat)", "estimasi_harga": 25000000 },
{ "nama_produk": "Mesin Jahit Industri Bekas", "estimasi_harga": 18000000 },
{ "nama_produk": "PC Rendering (Entry Level)", "estimasi_harga": 22000000 },
{ "nama_produk": "Biaya Pemasangan Kanopi Baja Ringan", "estimasi_harga": 16000000 },
{ "nama_produk": "Sofa Kulit Sintetis (3 Seater)", "estimasi_harga": 17000000 },
{ "nama_produk": "Kamera Sony A6400 (Body Only)", "estimasi_harga": 19000000 },
{ "nama_produk": "Arwana Super Red (Ukuran Sedang)", "estimasi_harga": 30000000 },
{ "nama_produk": "Biaya Sekolah Pilot (DP)", "estimasi_harga": 50000000 },

// Lanjutan Kategori: Rp 50.000.000 - Rp 100.000.000
{ "nama_produk": "Renovasi Dapur dan Kamar Mandi", "estimasi_harga": 80000000 },
{ "nama_produk": "DP Mobil Bekas (MPV)", "estimasi_harga": 60000000 },
{ "nama_produk": "Jam Tangan Swiss (Entry-Level Luxury)", "estimasi_harga": 90000000 },
{ "nama_produk": "Biaya Kuliah Kedokteran (Semester Awal)", "estimasi_harga": 75000000 },
{ "nama_produk": "Satu Set Drum Akustik Profesional", "estimasi_harga": 65000000 },

// Lanjutan Kategori: Di Atas Rp 100.000.000
{ "nama_produk": "Investasi Reksadana Saham (Modal Awal)", "estimasi_harga": 100000000 },
{ "nama_produk": "Mobil Sedan Bekas (Vios/City)", "estimasi_harga": 120000000 },
{ "nama_produk": "Biaya Franchise Kopi Ternama (Paket Awal)", "estimasi_harga": 150000000 },
{ "nama_produk": "Tanah Kavling di Pinggir Kota (per 100m2)", "estimasi_harga": 180000000 },
{ "nama_produk": "Motor Sport 250cc Baru (Kawasaki/Honda)", "estimasi_harga": 130000000 },
// Lanjutan Kategori: Di Bawah Rp 10.000
{ "nama_produk": "Isi Pensil Mekanik", "estimasi_harga": 6000 },
{ "nama_produk": "Klip Kertas (1 box)", "estimasi_harga": 5000 },
{ "nama_produk": "Kecap Manis Sachet", "estimasi_harga": 1000 },
{ "nama_produk": "Saus Sambal Sachet", "estimasi_harga": 1000 },
{ "nama_produk": "Cuka Dapur Botol Kecil", "estimasi_harga": 4000 },
{ "nama_produk": "Kemiri (1 ons)", "estimasi_harga": 7000 },
{ "nama_produk": "Ketumbar Bubuk Sachet", "estimasi_harga": 2000 },
{ "nama_produk": "Kapas Wajah", "estimasi_harga": 8000 },
{ "nama_produk": "Cotton Bud", "estimasi_harga": 5000 },
{ "nama_produk": "Tali Pramuka", "estimasi_harga": 9000 },
{ "nama_produk": "Buku Saku/Notes Kecil", "estimasi_harga": 6500 },
{ "nama_produk": "Penjepit Kertas (Binder Clip)", "estimasi_harga": 7500 },

// Lanjutan Kategori: Rp 10.000 - Rp 50.000
{ "nama_produk": "Pembersih Lantai Pouch", "estimasi_harga": 12000 },
{ "nama_produk": "Sabun Cuci Piring Pouch", "estimasi_harga": 14000 },
{ "nama_produk": "Hand Sanitizer 50ml", "estimasi_harga": 18000 },
{ "nama_produk": "Kaus Kaki Sekolah", "estimasi_harga": 15000 },
{ "nama_produk": "Cutter Besar", "estimasi_harga": 11000 },
{ "nama_produk": "Selotip Bening Besar", "estimasi_harga": 10000 },
{ "nama_produk": "Piring Makan Keramik", "estimasi_harga": 25000 },
{ "nama_produk": "Cetakan Es Batu", "estimasi_harga": 20000 },
{ "nama_produk": "Sarung Bantal", "estimasi_harga": 30000 },
{ "nama_produk": "Susu Kental Manis Kaleng", "estimasi_harga": 13000 },
{ "nama_produk": "Kopi Bubuk 100g", "estimasi_harga": 16000 },
{ "nama_produk": "Sarden Kaleng", "estimasi_harga": 22000 },

// Lanjutan Kategori: Rp 50.000 - Rp 250.000
{ "nama_produk": "Mug Custom dengan Foto", "estimasi_harga": 75000 },
{ "nama_produk": "Topi Trucker/Jaring", "estimasi_harga": 60000 },
{ "nama_produk": "Celana Pendek Olahraga", "estimasi_harga": 90000 },
{ "nama_produk": "Mousepad Gaming (Ukuran Sedang)", "estimasi_harga": 120000 },
{ "nama_produk": "Termometer Infrared", "estimasi_harga": 180000 },
{ "nama_produk": "Food Processor Mini", "estimasi_harga": 220000 },
{ "nama_produk": "Celemek Masak", "estimasi_harga": 55000 },
{ "nama_produk": "Lampu Darurat (Emergency Lamp)", "estimasi_harga": 110000 },
{ "nama_produk": "Kacamata Anti Radiasi", "estimasi_harga": 150000 },
{ "nama_produk": "Speaker Bluetooth Kecil", "estimasi_harga": 130000 },
{ "nama_produk": "Rak Dinding Ambalan", "estimasi_harga": 85000 },
{ "nama_produk": "Gembok Cakram Motor", "estimasi_harga": 100000 },

// Lanjutan Kategori: Rp 250.000 - Rp 1.000.000
{ "nama_produk": "Gerinda Tangan", "estimasi_harga": 450000 },
{ "nama_produk": "Sepatu Safety (Pengaman)", "estimasi_harga": 380000 },
{ "nama_produk": "Ransel Gunung (Carrier) 45L", "estimasi_harga": 500000 },
{ "nama_produk": "Kompor Portable untuk Camping", "estimasi_harga": 280000 },
{ "nama_produk": "Jubah Mandi (Bathrobe)", "estimasi_harga": 300000 },
{ "nama_produk": "Digital Painting Tablet (Pen Tablet)", "estimasi_harga": 700000 },
{ "nama_produk": "Mesin Pembuat Kopi (Coffee Maker)", "estimasi_harga": 650000 },
{ "nama_produk": "Hoodie Polos Berkualitas", "estimasi_harga": 320000 },
{ "nama_produk": "Lampu Studio Ringan (Ring Light)", "estimasi_harga": 400000 },
{ "nama_produk": "Ampli Gitar Mini", "estimasi_harga": 800000 },
{ "nama_produk": "Pembersih Udara (Air Humidifier)", "estimasi_harga": 350000 },

// Lanjutan Kategori: Rp 1.000.000 - Rp 5.000.000
{ "nama_produk": "Showcase Pendingin Minuman", "estimasi_harga": 3500000 },
{ "nama_produk": "Meja Kasir Sederhana", "estimasi_harga": 1800000 },
{ "nama_produk": "Lemari Arsip Besi", "estimasi_harga": 2200000 },
{ "nama_produk": "Mesin Bor Duduk", "estimasi_harga": 1500000 },
{ "nama_produk": "Sofa Bed Single", "estimasi_harga": 2800000 },
{ "nama_produk": "Stabilizer (Stavolt) 1000VA", "estimasi_harga": 1100000 },
{ "nama_produk": "Asuransi Kesehatan (Premi per bulan)", "estimasi_harga": 1200000 },
{ "nama_produk": "Handphone Second (iPhone XR/XS)", "estimasi_harga": 4500000 },
{ "nama_produk": "Kursus Online Bersertifikat", "estimasi_harga": 3000000 },
{ "nama_produk": "Down Payment (DP) Motor Listrik", "estimasi_harga": 2500000 },

// Lanjutan Kategori: Rp 5.000.000 - Rp 15.000.000
{ "nama_produk": "Kanopi Teras Rumah Minimalis", "estimasi_harga": 8000000 },
{ "nama_produk": "Perbaikan Cat Mobil (per Panel)", "estimasi_harga": 6000000 },
{ "nama_produk": "Samsung Galaxy A Series Terbaru", "estimasi_harga": 7000000 },
{ "nama_produk": "Biaya Servis Besar Mobil", "estimasi_harga": 5500000 },
{ "nama_produk": "Gerobak Motor untuk Usaha", "estimasi_harga": 9000000 },
{ "nama_produk": "Sumur Bor (hingga 30 meter)", "estimasi_harga": 12000000 },
{ "nama_produk": "Kambing Kurban (Tipe Super)", "estimasi_harga": 6500000 },
{ "nama_produk": "Komputer Rakitan Gaming (Entry)", "estimasi_harga": 11000000 },
{ "nama_produk": "Sewa Ruko Kecil (per bulan)", "estimasi_harga": 10000000 },
{ "nama_produk": "Spring Bed King Size (Full Set)", "estimasi_harga": 13000000 },

// Lanjutan Kategori: Rp 15.000.000 - Rp 50.000.000
{ "nama_produk": "Biaya Pasang AC Sentral (1 Titik)", "estimasi_harga": 25000000 },
{ "nama_produk": "DP Rumah Subsidi", "estimasi_harga": 18000000 },
{ "nama_produk": "Paket Sound System Panggung Kecil", "estimasi_harga": 30000000 },
{ "nama_produk": "Sapi Kurban (Tipe Limosin)", "estimasi_harga": 28000000 },
{ "nama_produk": "Modal Usaha Angkringan Modern", "estimasi_harga": 20000000 },
{ "nama_produk": "Biaya Balik Nama Sertifikat Rumah", "estimasi_harga": 16000000 },
{ "nama_produk": "Motor Matic 150cc Bekas", "estimasi_harga": 19000000 },
{ "nama_produk": "Biaya Pemasangan Tandon Air Stainless", "estimasi_harga": 17000000 },

// Lanjutan Kategori: Rp 50.000.000 - Rp 100.000.000
{ "nama_produk": "Modal Usaha Warung Sembako", "estimasi_harga": 60000000 },
{ "nama_produk": "Mobil City Car Bekas (di atas 10 tahun)", "estimasi_harga": 75000000 },
{ "nama_produk": "Renovasi Teras dan Taman", "estimasi_harga": 55000000 },
{ "nama_produk": "DP Mobil Bekas (Avanza/Xenia)", "estimasi_harga": 70000000 },
{ "nama_produk": "Biaya Pernikahan di KUA + Syukuran Sederhana", "estimasi_harga": 65000000 },
{ "nama_produk": "Modal Awal Ternak Lele Sistem Bioflok", "estimasi_harga": 80000000 },
{ "nama_produk": "Biaya Pendidikan Anak (Uang Pangkal SD Swasta)", "estimasi_harga": 90000000 },


// Lanjutan Kategori: Di Bawah Rp 10.000
{ "nama_produk": "Cat Air Eceran (1 tube)", "estimasi_harga": 7000 },
{ "nama_produk": "Kuas Lukis Kecil", "estimasi_harga": 5000 },
{ "nama_produk": "Lilin Aromaterapi Kecil", "estimasi_harga": 9000 },
{ "nama_produk": "Bibit Tanaman (Sachet)", "estimasi_harga": 8000 },
{ "nama_produk": "Double Tape Busa", "estimasi_harga": 6000 },
{ "nama_produk": "Isolasi Listrik", "estimasi_harga": 7500 },
{ "nama_produk": "Minyak Angin Aromatherapy", "estimasi_harga": 9500 },
{ "nama_produk": "Permen Pelega Tenggorokan", "estimasi_harga": 8500 },
{ "nama_produk": "Kertas Minyak Wajah", "estimasi_harga": 7000 },
{ "nama_produk": "Bawang Goreng (Sachet)", "estimasi_harga": 4000 },
{ "nama_produk": "Pita Kado Gulung", "estimasi_harga": 5500 },

// Lanjutan Kategori: Rp 10.000 - Rp 50.000
{ "nama_produk": "Senar Gitar Akustik (1 Set)", "estimasi_harga": 45000 },
{ "nama_produk": "Kanvas Lukis 20x20cm", "estimasi_harga": 20000 },
{ "nama_produk": "Pick Gitar (Set isi 5)", "estimasi_harga": 15000 },
{ "nama_produk": "Buku Resep Masakan", "estimasi_harga": 48000 },
{ "nama_produk": "Pupuk NPK 1kg", "estimasi_harga": 25000 },
{ "nama_produk": "Semprotan Hama Tanaman", "estimasi_harga": 30000 },
{ "nama_produk": "Stop Kontak 4 Lubang", "estimasi_harga": 40000 },
{ "nama_produk": "Sekop Taman Kecil", "estimasi_harga": 28000 },
{ "nama_produk": "Cetakan Kue Silikon", "estimasi_harga": 35000 },
{ "nama_produk": "Gelas Takar", "estimasi_harga": 18000 },
{ "nama_produk": "Sarung Tangan Cuci Piring", "estimasi_harga": 22000 },
{ "nama_produk": "Kabel Audio AUX", "estimasi_harga": 25000 },

// Lanjutan Kategori: Rp 50.000 - Rp 250.000
{ "nama_produk": "Cat Akrilik Set (12 Warna)", "estimasi_harga": 90000 },
{ "nama_produk": "Stand Buku / Penyangga Buku", "estimasi_harga": 70000 },
{ "nama_produk": "Papan Catur Lipat Kayu", "estimasi_harga": 150000 },
{ "nama_produk": "Capo Gitar", "estimasi_harga": 60000 },
{ "nama_produk": "Lampu Tumblr (Lampu Hias)", "estimasi_harga": 55000 },
{ "nama_produk": "Tas Belanja Lipat (Reusable Bag)", "estimasi_harga": 65000 },
{ "nama_produk": "Rak Kosmetik Meja", "estimasi_harga": 120000 },
{ "nama_produk": "Senter LED", "estimasi_harga": 100000 },
{ "nama_produk": "Toolkit Set Mini", "estimasi_harga": 180000 },
{ "nama_produk": "Botol Termos Kopi", "estimasi_harga": 160000 },
{ "nama_produk": "Borgol Mainan", "estimasi_harga": 80000 },
{ "nama_produk": "Kipas Angin USB", "estimasi_harga": 95000 },

// Lanjutan Kategori: Rp 250.000 - Rp 1.000.000
{ "nama_produk": "Ukulele Konser", "estimasi_harga": 450000 },
{ "nama_produk": "Stand Mikrofon", "estimasi_harga": 300000 },
{ "nama_produk": "Timbangan Kopi Digital", "estimasi_harga": 280000 },
{ "nama_produk": "Lensa HP (Clip-On Kit)", "estimasi_harga": 260000 },
{ "nama_produk": "Exhaust Fan Dinding", "estimasi_harga": 350000 },
{ "nama_produk": "Pistol Lem Tembak", "estimasi_harga": 270000 },
{ "nama_produk": "Mesin Gerinda Mini", "estimasi_harga": 400000 },
{ "nama_produk": "Toaster / Pemanggang Roti", "estimasi_harga": 320000 },
{ "nama_produk": "Keyboard Bluetooth Portable", "estimasi_harga": 420000 },
{ "nama_produk": "Lampu Gantung Hias", "estimasi_harga": 500000 },
{ "nama_produk": "Karpet Bulu Ruang Tamu", "estimasi_harga": 600000 },

// Lanjutan Kategori: Rp 1.000.000 - Rp 5.000.000
{ "nama_produk": "Mesin Pembuat Es Krim", "estimasi_harga": 2500000 },
{ "nama_produk": "Proyektor Mini Portable", "estimasi_harga": 1800000 },
{ "nama_produk": "Set Pisau Dapur Profesional", "estimasi_harga": 1200000 },
{ "nama_produk": "Water Heater Listrik (Kapasitas Kecil)", "estimasi_harga": 2200000 },
{ "nama_produk": "Meja TV Minimalis", "estimasi_harga": 1500000 },
{ "nama_produk": "Teleskop Refraktor", "estimasi_harga": 3000000 },
{ "nama_produk": "Sepatu Roda / Inline Skate", "estimasi_harga": 1100000 },
{ "nama_produk": "Kasur Lipat", "estimasi_harga": 1300000 },
{ "nama_produk": "Lemari Plastik Pakaian", "estimasi_harga": 1400000 },

// Lanjutan Kategori: Rp 5.000.000 - Rp 15.000.000
{ "nama_produk": "Kulkas Mini Bar", "estimasi_harga": 5500000 },
{ "nama_produk": "Meja Kerja Standing Desk Manual", "estimasi_harga": 6000000 },
{ "nama_produk": "iPad Bekas (Generasi 7/8)", "estimasi_harga": 7000000 },
{ "nama_produk": "Mesin Pemotong Rumput Gendong", "estimasi_harga": 5800000 },
{ "nama_produk": "Biola Elektrik", "estimasi_harga": 8000000 },
{ "nama_produk": "Sewa Apartemen Studio (per bulan)", "estimasi_harga": 9000000 },
{ "nama_produk": "Paket Katering Sehat (1 bulan)", "estimasi_harga": 6500000 },
{ "nama_produk": "Handphone Flagship Bekas (2 tahun lalu)", "estimasi_harga": 10000000 },
{ "nama_produk": "Papan Selancar (Surfboard)", "estimasi_harga": 7500000 },

// Lanjutan Kategori: Rp 15.000.000 - Rp 50.000.000
{ "nama_produk": "Paket Liburan ke Labuan Bajo (per orang)", "estimasi_harga": 18000000 },
{ "nama_produk": "DP Motor Custom", "estimasi_harga": 20000000 },
{ "nama_produk": "Renovasi 1 Kamar Tidur (Full)", "estimasi_harga": 25000000 },
{ "nama_produk": "Biaya Lisensi Software Desain (1 tahun)", "estimasi_harga": 16000000 },
{ "nama_produk": "Sistem Hidroponik Skala Rumahan (Lengkap)", "estimasi_harga": 19000000 },
{ "nama_produk": "Sepeda Gunung Full Suspension (Entry)", "estimasi_harga": 22000000 },
{ "nama_produk": "Biaya Membuat Website E-commerce", "estimasi_harga": 30000000 },
{ "nama_produk": "Kamera Pocket Full Frame (Sony RX1)", "estimasi_harga": 28000000 },

// Lanjutan Kategori: Rp 50.000.000 - Rp 100.000.000
{ "nama_produk": "Modal Awal Coffee Shop Kecil", "estimasi_harga": 85000000 },
{ "nama_produk": "Food Truck Bekas (Kosongan)", "estimasi_harga": 70000000 },
{ "nama_produk": "Biaya Daftar Ibadah Haji (Waiting List)", "estimasi_harga": 60000000 },
{ "nama_produk": "DP Mobil MPV Baru (Calya/Sigra)", "estimasi_harga": 75000000 },
{ "nama_produk": "Membeli Waralaba Minuman Terkenal", "estimasi_harga": 95000000 },
{ "nama_produk": "Sewa Ruko 1 Tahun di Lokasi Strategis", "estimasi_harga": 80000000 },
{ "nama_produk": "Membeli Kebun Kecil (di Desa)", "estimasi_harga": 100000000 }

];
